# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4690e6a35763e1c5cb3ea0c8d75b5a8916bbb31d35ad88689a6ce0c50e699b4dd74d33b6fd09f99aee4639515386f87a9465f155a4c6df2aa1b7b187ed361d5c

test:
  secret_key_base: 7884799ce77787268b28c117a5116e0cc7e11b1acd29eda536fa39f3f4c63ffa436a3402575cf3a1902950f929800032b8a293a04883ded966499a55f83f6a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
